name: Run Tests

on:
  push

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
   
    - name: Set up Python
      uses: actions/setup-python@v2  
      with: 
        python-version: '3.x'

    - name: Install Python requirements for tests
      run: python -m pip install -r tests/test-requirements.txt

    - name: Run Tests 
      run: python -m unittest discover tests
